language: go
go:
  - 1.17

script: go test -v ./...
install: true
before_deploy:
- make release-bin
deploy:
  provider: releases
  api_key:
    secure: "fZCvDE+H1vw6OOzw+3j7O+TgkSeEC0jXR0CgiILXi/I/TKSGCw0HVo8cQMt388AxGOesLYUAXiLilEuz+7KlrXv3NHh63S7DUGL8AVU010kLflH8qr0WO5pDkSVrs3E25csYcVKDvdLUw7TKPxsyy66LjMRl5NDpfVmDOTqaj+jPuWp2wVC9X45NL5pFd7vw1VDXHU74ldGIYEGGRJZRKmgw4CNgIYQLVClD4SP/k7BG6W0U12UM58+yzCaPvVI0B0wYNyBp2pouQMiIkIAj4BZcxdJbseCZpeippkbaP1Sn9NA9WkLVafrkmDf9yx1RASo1ClK9dN0Sr30rMiihHTWwejEQ9dIDUx4JlreRRLufUI7VDLov/eFDUyensIGUDIYhWHOm98DxJWfMYv9BEAWoC5ywPdmjZbeH6nGwfQYlBiaSDthGfIJj21nIvUL/4YZRf1oPaWYwVJT3IWcBozf+oHpzJZL4qGTs7wQCKZ0HghrQ1UDVG2m9rB+sAkpxv+aQGPFMDyvgxsTNX56lcuGkl7I7Fcl0jsF2EVSqBRN9Fg5ZCrtFBNd9nbxGNDdMZjIPD38BAIO1uT60XCD0GxEOn5FzVatzWjhxys/KW+DJG6+KxCS8wL/+bGGgRNM0dYCa0Hw4vIZbl6VEqNTuAWXKrJivxe4weyZfz95mqbw="
  file_glob: true
  file: "./build/*"
  skip_cleanup: true
  draft: true
#  on:
#    tags: true
