language: go
go:
- 1.17.7
script: go test -v ./...
install: true
before_deploy:
- make release-bin
deploy:
  provider: releases
  api_key:
    secure: RAyiN7sWzOvAJBA9Q5MkbAWlo5aVU6XRt9PPcbvbUM5g/iXwwWZre/MquTBOHJtS9Tw8irys4Zqa8vYwOszvmONCk1j+vPrAu2S2YRtrUk5zMA4hT6xqNC36JwRLFk8ztWxBmriz+HTOd08NX2Qmym6Z2a6OGPtReuAPV17dcTpE4cMFwT7WWNISf8LheRxCpS2j1UQBC6tVuc8DUFASdoBE3qJlr7Beewp7Y2ZAQTChTf/PsfvhbQFWyH1lutEzMrQCPguuLheV88DA9iGSMs8D8S5u/RwhCbe2RAXbYkPabN/ihk42Cd24gCxIcpovSofJm1fLIaBpVeV8SHD/ljLG6WIcHbsk9SQPgGwyv7CqxiaLM3ZFrgg/AOh8md0KmvhSIcr1aIIyIk6+5IrGaTyQniBnAUFTxN73YwljHRi2jge5gZKehD00Sh257gfcB5TYmTwAow2S2vNv4oc3Qd3EMWBdnFlhSOWYyFESBnEKgwQKl9tgfaVFcGG6ImjumXyoxx34+N+wg0Pyjt8xJXqxiUs57T4/H9+rvFAxFQGOWDpzsDbgY8g4EBBoATRZWMXI43RQqaFiVgIez+hBf2Fv2ptmAmvd/DhCeUle9SZvBPDHa2g6zbTB9T/pCiv0XwQIynOEqjK9KZVz7tgqWQm7BSt63WGGQAwEz3dxtMk=
  file: './build/*'
  file_glob: true
  on:
    tags: true
    repo: actano/helm-sealed-secrets
  skip_cleanup: 'true'
env:
  global:
    secure: 0WFjikke8+Jo/o9fT2LURgBT6N0UIqy+GZmLJkrDdRIgWar9ejZM7Nua93MIacJCKHGWPiHv1znuN6PnEi+l9TWuVK/kviWGGnZJci3LmZEBtZ86Xb3lXX0gKXv5xoCWDlPRAVazRDg4IeQomrO5tmgWmWzOcWuM4YtZh85csWnpRjiG/zeoZgAFpKD2Df4eFn6RM3xBKvrQYWXQrfTdrrtT59uq9ZUpJouODLCMNw2t0qyort0s4vMKKgPv/tNgRAJjxvdfyeBIFz4Dko4B6AtxqQ1lo49cI+JjHeNsgCGQWcTeBb81KM0Fdc6mugPduTX8us3McRbjW2mEXbB86TAK86JWetMiZJ4TP9taVSlLtK7icxbwweM9uwhFZjnWivzHDxZ7/u1bSoDYgGT96Vu174EEwN9HiaawvIjA9nlyVEUmeGBbBL74CMn6lkI9CkUs3zrbBtwXW3gRSReBvs+BhDTUoXenJA5Zt4RYE1Al5I4YEnf8dTObORbMlyvLaoRpAclKBbwq089XBFrLYocaKQUlC1ui0NrfAKUhe2YlOqqGYPjblIREi4O2EjxBnBFSgZUDYUv0s2pgqMu0K7F4PcmLqNG6XKOHgKCb/C1U7TkW3V3yUS6iqhnjbyRB/H322BWx9d+CwOpDnbIRn7QxijIhOV0u/3mqQ7LThy8=
