language: go
go:
  - 1.17

script: go test -v ./...
install: true
before_deploy:
- make release-bin
deploy:
  provider: releases
  api_key:
    secure: "elPHMW9LHwgk24afSKSMi9ubG6v7f37YYV7vmLGjk5vnuTTomQL6uWKrxvGfr0QJAHpyy6Ug9OSwGoA1AVtUAsLwQBD5brd5e4B0Ocb6RVVPuy1Kd7Uk0YacMggGRXM+oN7EjnLKUJSzS+Vmh/utFdt3zb64BkHcr1qXtWMzVt8Qur1UyZwLKp9EHGHsux/3yGdUwtzPcCUteN4PpM7MQI88AJ4fuqh43ceKCfroxtut/aJVbbm2dM7cV3ArlWWxl+JbShdAfBCmyUN2WJD9e6kai+FIKcrNuSGBTx6Ke8CP3pCKOsySV3O2ufJfKfHOJ7PHsQqzMPvljYusqAlq6JajVq1o2pPG/ygViN2f6OXNw2LaI51W+NohhC7vxOuAH5GssfSGRbzFo//Zh++e3gx/dSzQ2PEGOoxcQJlfduGDoT/HMEt9bt1aL2n/3vbOTVHHyWUqTmJQjqhqrZwoHYbDBRD1Q9bZhKACIGhBwl7fVH/aed+QRlzY4ZrzM4gRRXCeevZ3AeLGU0T4YeMJ5O684W+siY28V/Lk1sxtHprYrEX7jxhTzY2XNNNiQxkZscfetRxTAUGcX0fLuexiIH5YAZRG/LN332LWqKZxtUUlitZeiwNjiGdjnCUP4fwT3jQwhwsFLsqgoaTDzUrrPAcwXMvOofTDP+yYHhwZW0g="
  file_glob: true
  file: "./build/*"
  skip_cleanup: true
  draft: true
#  on:
#    tags: true
