name: sealed-secrets
version: 1.0.0
usage: Sealed Secrets encryption in Helm for Git storing
description: |-
  This plugin provides secrets values encryption for Helm charts using the sealed-secrets tool
  (https://github.com/bitnami-labs/sealed-secrets).
command: $HELM_PLUGIN_DIR/sealed-secrets.sh
useTunnel: true
