name: sealed-secrets
version: 0.1.5
usage: Sealed Secrets encryption in Helm for Git storing
description: |-
  This plugin provides secrets values encryption for Helm charts using the sealed-secrets tool
  (https://github.com/bitnami-labs/sealed-secrets).
command: helm-sealed-secrets
useTunnel: false
hooks:
  install: $HELM_PLUGIN_DIR/install-binary.sh
  update: $HELM_PLUGIN_DIR/install-binary.sh
