name: vault-template
version: v0.1.3
usage: Render a template file with Vault paths to a file
description: |-
  This plugin intergrates with Vault to render a template file with Vault paths to a file. Useful to prepare a values.yaml file to deploy a helm chart.
command: $HELM_PLUGIN_DIR/helm-vault-template
useTunnel: false
hooks:
  install: $HELM_PLUGIN_DIR/install-binary.sh
  update: $HELM_PLUGIN_DIR/install-binary.sh
