name: Go

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GO111MODULE: "on"
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      - name: Install all Go dependencies
        run: |
          go get

      - name: Build
        run: make release-bin

      - name: Create release
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/tcnksm/ghr
          ghr -t ${{ secrets.GITHUB_TOKEN }} -c ${{ github.ref }} -delete ${{ github.ref }} ./build
