name: Go

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GO111MODULE: "on"
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      - name: Install all Go dependencies
        run: go get

      - name: Build
        run: make release-bin

      - name: Create release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          allow_override: true
          files: ./build/
